const API="https://script.google.com/macros/s/AKfycbxO5nf0N0IF3YIPCLREDRLFrhIU9bWhadfrjhtLb5vT8ZRFiv_ffkZQRO-QL6VqASMsHA/exec";
let token=localStorage.getItem("pefso_token")||"", me=null, customers=[],deals=[],products=[],selectedProducts=new Set();

const DEMO_CUSTOMERS=[
{customer_id:'CUST-DEMO-001',company_name:'DEMO Party Supply USA',website:'https://party-supply-demo.example',domain:'party-supply-demo.example',country:'United States',contact_name:'Alex Carter',contact_email:'alex.carter@party-supply-demo.example',owner_user_id:'ctv1',account_status:'Protected',active:true},
{customer_id:'CUST-DEMO-002',company_name:'DEMO Celebration Retail UK',website:'https://celebration-retail-demo.example',domain:'celebration-retail-demo.example',country:'United Kingdom',contact_name:'Emma Reed',contact_email:'emma.reed@celebration-retail-demo.example',owner_user_id:'ctv2',account_status:'Assigned',active:true},
{customer_id:'CUST-DEMO-003',company_name:'DEMO Fiesta Import Mexico',website:'https://fiesta-import-demo.example',domain:'fiesta-import-demo.example',country:'Mexico',contact_name:'Sofia Martinez',contact_email:'sofia@fiesta-import-demo.example',owner_user_id:'staff',account_status:'Assigned',active:true},
{customer_id:'CUST-DEMO-004',company_name:'DEMO Event Wholesale Australia',website:'https://event-wholesale-demo.example',domain:'event-wholesale-demo.example',country:'Australia',contact_name:'Liam Walker',contact_email:'liam.walker@event-wholesale-demo.example',owner_user_id:'ctv1',account_status:'Protected',active:true},
{customer_id:'CUST-DEMO-005',company_name:'DEMO Nordic Party AB',website:'https://nordic-party-demo.example',domain:'nordic-party-demo.example',country:'Sweden',contact_name:'Elsa Lind',contact_email:'elsa@nordic-party-demo.example',owner_user_id:'ctv2',account_status:'Assigned',active:true}
];
const DEMO_DEALS=[
{deal_id:'DEAL-DEMO-001',customer_id:'CUST-DEMO-001',deal_name:'US 20ft Balloon Weight Program',owner_user_id:'ctv1',stage:'Quotation',status:'Open',estimated_qty:97000,next_action:'Send quotation V1',next_action_date:'2026-08-21',active:true},
{deal_id:'DEAL-DEMO-002',customer_id:'CUST-DEMO-002',deal_name:'UK Rose Gold & Iridescent Range',owner_user_id:'ctv2',stage:'Proposal',status:'Open',estimated_qty:120000,next_action:'Confirm retail packing requirement',next_action_date:'2026-08-22',active:true},
{deal_id:'DEAL-DEMO-003',customer_id:'CUST-DEMO-003',deal_name:'Mexico Mixed Color Trial',owner_user_id:'staff',stage:'Qualified',status:'Open',estimated_qty:150000,next_action:'Validate mixed-SKU loading',next_action_date:'2026-08-24',active:true},
{deal_id:'DEAL-DEMO-004',customer_id:'CUST-DEMO-004',deal_name:'Australia Sample + Quote',owner_user_id:'ctv1',stage:'Sample',status:'Open',estimated_qty:97000,next_action:'Confirm approved foil shade',next_action_date:'2026-08-25',active:true},
{deal_id:'DEAL-DEMO-005',customer_id:'CUST-DEMO-005',deal_name:'Nordic Gold/Silver Program',owner_user_id:'ctv2',stage:'Won',status:'Won',estimated_qty:200000,next_action:'Commission estimate',next_action_date:'2026-08-19',active:true},
{deal_id:'DEAL-DEMO-006',customer_id:'CUST-DEMO-003',deal_name:'Mexico Price Test — Lost',owner_user_id:'staff',stage:'Lost',status:'Lost',estimated_qty:97000,next_action:'Revisit next season',next_action_date:'2026-09-15',active:true}
];
const DEMO_PRODUCTS=[['112725.01','Blue','1guePy7dZW3jJyLlwG42IwR6beTTDoAUF'],['112725.03','Green','1HJQX5MsQ6ONQ1FqijOwdkr4LxcZlnECX'],['112725.05','Orange','1AnB_Xy9klJBDx1r9SJjvtKalD2AHQgGP'],['112725.06','Pink','1wHroEum17z9V_PMm6QKRql_SdnabdJkv'],['112725.07','Red','1IeFPJjTWo7YI919kJEz67U7P86SjehKz'],['112725.10','Black','1aZis2Lzm8XSvgdfwvvjERAWEUssiyX2X'],['112725.14','Purple','1xsv-XyZJ3HSbOi3YHinnhecYRQVu4ZwY'],['112725.143','Rose Gold','1O_6scSbzw23ZM544LMY6vSy9sx9LI60n'],['112725.15','Iridescent','1manRmkBp5ZaDjr_hde4JfdTyYMNibaIN'],['112725.16','Bright Pink','1MPFYf-n5yLY1KHbO4xp6zBjJqh1seBpq'],['112725.18','Silver','1oAM4yXSBt06BXy4CAlxtbsenny3HPRcA'],['112725.19','Gold','1neFIk0a2MMm9haPJGDdHvs5c3i2EuOGh'],['112725.54','Aqua / Teal','1681yiQmc7kPkEkZks7WuKy1_bdQ1eUdq']].map(x=>({product_id:'BW-'+x[0],item_code:x[0],product_name:'Small Foil Balloon Weight',color:x[1],moq_pcs:97000,expected_fob_usd:.134375,floor_fob_usd:.123625,image_url:`https://drive.google.com/thumbnail?id=${x[2]}&sz=w600`,status:'Active'}));
const DEMO_QUOTES=[
{quotation_id:'Q-DEMO-001',quotation_no:'QT-DEMO-001',version:1,buyer_company:'DEMO Party Supply USA',item_code:'112725.01',color:'Blue',quantity:97000,requested_unit_price:.138,status:'Pending Approval'},
{quotation_id:'Q-DEMO-002',quotation_no:'QT-DEMO-002',version:2,buyer_company:'DEMO Nordic Party AB',item_code:'112725.19',color:'Gold',quantity:200000,requested_unit_price:.141,approved_unit_price:.141,status:'Approved'},
{quotation_id:'Q-DEMO-003',quotation_no:'QT-DEMO-003',version:1,buyer_company:'DEMO Celebration Retail UK',item_code:'112725.143',color:'Rose Gold',quantity:120000,requested_unit_price:.142,status:'Draft'}
];
const DEMO_ACTIVITIES=[
{timestamp:'2026-08-19',user_id:'ctv1',activity_type:'Email sent',channel:'Email',summary:'Sent initial Balloon Weight range and MOQ.'},
{timestamp:'2026-08-19',user_id:'ctv2',activity_type:'Customer replied',channel:'Email',summary:'Buyer asked about private label and rose gold.'},
{timestamp:'2026-08-18',user_id:'staff',activity_type:'Call',channel:'Call',summary:'Qualified Mexico mixed-color trial.'},
{timestamp:'2026-08-18',user_id:'ctv1',activity_type:'Sample discussion',channel:'WhatsApp',summary:'Confirmed green/aqua shade review.'},
{timestamp:'2026-08-17',user_id:'ctv2',activity_type:'Negotiation',channel:'Video call',summary:'Discussed Gold/Silver program at USD 0.141.'}
];

const $=id=>document.getElementById(id), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function scopedDemo(list){if(!me||me.role!=='collaborator')return list;return list.filter(x=>(x.owner_user_id||x.user_id)===me.user_id)}
function cacheSet(k,v){try{localStorage.setItem('pefso_'+k,JSON.stringify({t:Date.now(),v}))}catch{}}
function cacheGet(k){try{const x=JSON.parse(localStorage.getItem('pefso_'+k)||'null');return x&&Date.now()-x.t<300000?x.v:null}catch{return null}}
async function api(action,p={}){const r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,token,...p})});return r.json()}
async function apiFast(action,p={},ms=3000){const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),ms);try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token,...p}),signal:ctl.signal});return await r.json()}finally{clearTimeout(tm)}}
function message(id,t,ok=false){const e=$(id);if(!e)return;e.textContent=t||"";e.className="msg "+(ok?"ok":"err")}
function can(k){return me&&me.permissions&&(me.permissions[k]===true||String(me.permissions[k])==="true")}
function admin(){return me&&me.role==="admin"} function staff(){return me&&me.role==="staff"}
function closeModal(){$("modal").classList.add("hidden")} function modal(title,body){$("modalTitle").textContent=title;$("modalBody").innerHTML=body;$("modal").classList.remove("hidden")}
function go(tab){document.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));document.querySelectorAll(".section").forEach(s=>s.classList.toggle("active",s.id===tab));if(tab==="dashboard")loadDashboard();if(tab==="customers")loadCustomers();if(tab==="deals")loadDeals();if(tab==="products")loadProducts();if(tab==="quotation")loadQuotes();if(tab==="activity")loadActivities();if(tab==="users")loadUsers();if(tab==="audit")loadAudit()}
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>go(b.dataset.tab));
$("loginBtn").onclick=async()=>{const pin=$("loginPin").value.trim();if(!/^\d{8}$/.test(pin))return message("loginMsg","PIN must be exactly 8 digits");try{const r=await api("login",{user_id:$("loginId").value.trim(),pin});if(!r.ok)throw Error(r.error);token=r.token;localStorage.setItem("pefso_token",token);showApp(r.user)}catch(e){message("loginMsg",e.message)}}
$("logoutBtn").onclick=async()=>{try{await apiFast("logout",{},1500)}catch{}localStorage.removeItem("pefso_token");location.reload()}
async function boot(){if(!token)return;try{const r=await apiFast("me",{},2500);if(r.ok)showApp(r.user)}catch{}}
async function showApp(u){me=u;customers=scopedDemo(cacheGet("customers")||DEMO_CUSTOMERS);deals=scopedDemo(cacheGet("deals")||DEMO_DEALS);products=cacheGet("products")||DEMO_PRODUCTS;$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("who").textContent=(u.display_name||u.user_id)+" · "+u.role;$("ownId").value=u.user_id;$("usersTab").classList.toggle("hidden",!can("can_manage_users"));$("auditTab").classList.toggle("hidden",!admin());$("addProductBtn").classList.toggle("hidden",!can("can_manage_products"));fillSelects();loadDashboard();refreshCore()}
async function refreshCore(){const jobs=[['customers','listCustomers',r=>r.customers],['deals','listDeals',r=>r.deals],['products','listProducts',r=>r.products]];await Promise.allSettled(jobs.map(async([k,a,pick])=>{try{const r=await apiFast(a);if(r&&r.ok){let v=pick(r);cacheSet(k,v);if(k==='customers')customers=v;if(k==='deals')deals=v;if(k==='products')products=v}}catch{}}));fillSelects()}
function fillSelects(){const cust=customers.filter(x=>x.active!==false&&String(x.active)!=="false");const co='<option value="">Select…</option>'+cust.map(c=>`<option value="${esc(c.customer_id)}">${esc(c.company_name)}</option>`).join("");["pCustomer","qCustomer","aCustomer"].forEach(id=>$(id).innerHTML=co);const dl='<option value="">Select…</option>'+deals.filter(d=>d.active!==false&&String(d.active)!=="false").map(d=>`<option value="${esc(d.deal_id)}">${esc(d.deal_name)}</option>`).join("");["pDeal","qDeal","aDeal"].forEach(id=>$(id).innerHTML=dl);$("qProduct").innerHTML='<option value="">Select…</option>'+products.filter(p=>String(p.status).toLowerCase()!=="deleted").map(p=>`<option value="${esc(p.product_id)}">${esc(p.item_code)} · ${esc(p.color)}</option>`).join("")}
async function loadDashboard(){const cs=scopedDemo(customers.length?customers:DEMO_CUSTOMERS),ds=scopedDemo(deals.length?deals:DEMO_DEALS),acts=scopedDemo(DEMO_ACTIVITIES);$("kCustomers").textContent=cs.filter(x=>String(x.active)!=='false').length;$("kDeals").textContent=ds.filter(x=>!['Won','Lost'].includes(x.stage)&&String(x.active)!=='false').length;$("kPending").textContent=DEMO_QUOTES.filter(x=>x.status==='Pending Approval').length;$("kActivities").textContent=acts.length;const users=me&&me.role==='collaborator'?[me.user_id]:['ctv1','ctv2','staff'];$("teamWrap").innerHTML='<table><tr><th>User</th><th>Activities</th><th>Customers</th><th>Open deals</th><th>Won</th></tr>'+users.map(u=>`<tr><td><b>${u}</b></td><td>${DEMO_ACTIVITIES.filter(a=>a.user_id===u).length}</td><td>${DEMO_CUSTOMERS.filter(c=>c.owner_user_id===u).length}</td><td>${DEMO_DEALS.filter(d=>d.owner_user_id===u&&!['Won','Lost'].includes(d.stage)).length}</td><td>${DEMO_DEALS.filter(d=>d.owner_user_id===u&&d.stage==='Won').length}</td></tr>`).join('')+'</table>';const pipe={};ds.forEach(d=>pipe[d.stage]=(pipe[d.stage]||0)+1);$("pipelineWrap").innerHTML='<div class="grid4">'+Object.entries(pipe).map(([k,v])=>`<div class="card kpi"><span>${esc(k)}</span><b>${v}</b></div>`).join('')+'</div>';try{const r=await apiFast('dashboard',{},2200);if(r.ok){$("kCustomers").textContent=r.kpi.customers;$("kDeals").textContent=r.kpi.open_deals;$("kPending").textContent=r.kpi.pending_quotes;$("kActivities").textContent=r.kpi.activities_7d}}catch{}}
function customerTable(list){return '<table><tr><th>Company</th><th>Country</th><th>Contact</th><th>Owner</th><th>Status</th><th></th></tr>'+list.map(c=>`<tr><td><b>${esc(c.company_name)}</b><div class="sub">${esc(c.domain||c.website||'')}</div></td><td>${esc(c.country||'')}</td><td>${esc(c.contact_name||'')}<div class="sub">${esc(c.contact_email||'')}</div></td><td>${esc(c.owner_user_id||'')}</td><td><span class="badge">${esc(c.account_status||'Active')}</span></td><td><button class="btn light sm" onclick='openCustomer(${JSON.stringify(JSON.stringify(c))})'>Edit</button></td></tr>`).join('')+'</table>'}
async function loadCustomers(render=true){const cached=scopedDemo(cacheGet("customers")||DEMO_CUSTOMERS);if(!customers.length)customers=cached;if(render)$("customersWrap").innerHTML=customerTable(customers);try{const r=await apiFast("listCustomers",{include_deleted:$("showDeletedCustomers")?.checked||false},2200);if(r.ok){customers=r.customers;cacheSet("customers",customers);if(render)$("customersWrap").innerHTML=customerTable(customers)}}catch{}return customers}
function openCustomer(js){const c=js?JSON.parse(js):{};const owners=(admin()||staff())?'<label>Owner</label><select id="mOwner">'+["staff","ctv","ctv1","ctv2"].map(x=>`<option ${c.owner_user_id===x?"selected":""}>${x}</option>`).join("")+'</select>':"";modal(c.customer_id?"Edit customer":"Add customer",`<input id="mCid" type="hidden" value="${esc(c.customer_id||"")}"><label>Company name *</label><input id="mCompany" value="${esc(c.company_name||"")}"><div class="grid2"><div><label>Website</label><input id="mWeb" value="${esc(c.website||"")}"></div><div><label>Country</label><input id="mCountry" value="${esc(c.country||"")}"></div></div><div class="grid2"><div><label>Contact name</label><input id="mContact" value="${esc(c.contact_name||"")}"></div><div><label>Contact email</label><input id="mEmail" value="${esc(c.contact_email||"")}"></div></div>${owners}<div class="note">Duplicate control uses website/email domain first, then company name + country.</div><button class="btn o full" onclick="saveCustomer()">Save customer</button><div id="mMsg" class="msg"></div>`)}
async function saveCustomer(){try{const r=await api("saveCustomer",{customer_id:$("mCid").value,company_name:$("mCompany").value,website:$("mWeb").value,country:$("mCountry").value,contact_name:$("mContact").value,contact_email:$("mEmail").value,owner_user_id:$("mOwner")?.value||me.user_id});if(!r.ok)throw Error(r.error);closeModal();await loadCustomers();fillSelects();loadDashboard()}catch(e){message("mMsg",e.message)}}
async function deleteCustomer(id){if(!confirm("Soft-delete this customer? The backend history will be retained."))return;await api("softDeleteCustomer",{customer_id:id});loadCustomers();loadDashboard()} async function restoreCustomer(id){await api("restoreCustomer",{customer_id:id});loadCustomers();loadDashboard()}
function dealTable(list){return '<table><tr><th>Deal</th><th>Customer</th><th>Owner</th><th>Stage</th><th>Qty</th><th>Next action</th></tr>'+list.map(d=>`<tr><td><b>${esc(d.deal_name)}</b></td><td>${esc(customerName(d.customer_id))}</td><td>${esc(d.owner_user_id)}</td><td><span class="badge">${esc(d.stage)}</span></td><td>${Number(d.estimated_qty||0).toLocaleString()}</td><td>${esc(d.next_action||'')}<div class="sub">${esc(d.next_action_date||'')}</div></td></tr>`).join('')+'</table>'}
async function loadDeals(render=true){if(render)$("dealsWrap").innerHTML=dealTable(deals.length?deals:scopedDemo(DEMO_DEALS));try{const r=await apiFast("listDeals",{include_deleted:$("showDeletedDeals")?.checked||false},2200);if(r.ok){deals=r.deals;cacheSet("deals",deals);if(render)$("dealsWrap").innerHTML=dealTable(deals)}}catch{}return deals}
function customerName(id){return customers.find(c=>c.customer_id===id)?.company_name||id||""}
function openDeal(js){const d=js?JSON.parse(js):{};const opts=customers.filter(c=>String(c.active)!=="false").map(c=>`<option value="${esc(c.customer_id)}" ${d.customer_id===c.customer_id?"selected":""}>${esc(c.company_name)}</option>`).join("");modal(d.deal_id?"Edit deal":"Add deal",`<input id="mDid" type="hidden" value="${esc(d.deal_id||"")}"><label>Customer *</label><select id="mDCustomer">${opts}</select><label>Deal name *</label><input id="mDName" value="${esc(d.deal_name||"")}"><div class="grid2"><div><label>Stage</label><select id="mDStage">${["Lead","Qualified","Proposal","Sample","Quotation","Negotiation","Won","Lost","On hold"].map(x=>`<option ${d.stage===x?"selected":""}>${x}</option>`).join("")}</select></div><div><label>Estimated quantity</label><input id="mDQty" type="number" value="${esc(d.estimated_qty||97000)}"></div></div><div class="grid2"><div><label>Target price USD/pc</label><input id="mDTarget" type="number" step="0.000001" value="${esc(d.customer_target_price_usd||"")}"></div><div><label>Destination port</label><input id="mDPort" value="${esc(d.destination_port||"")}"></div></div><label>Next action</label><input id="mDNext" value="${esc(d.next_action||"")}"><label>Next action date</label><input id="mDDate" type="date" value="${esc(String(d.next_action_date||"").slice(0,10))}"><button class="btn o full" onclick="saveDeal()">Save deal</button><div id="mMsg" class="msg"></div>`)}
async function saveDeal(){try{const r=await api("saveDeal",{deal_id:$("mDid").value,customer_id:$("mDCustomer").value,deal_name:$("mDName").value,stage:$("mDStage").value,estimated_qty:$("mDQty").value,customer_target_price_usd:$("mDTarget").value,destination_port:$("mDPort").value,next_action:$("mDNext").value,next_action_date:$("mDDate").value});if(!r.ok)throw Error(r.error);closeModal();loadDeals();loadDashboard()}catch(e){message("mMsg",e.message)}}
async function deleteDeal(id){if(confirm("Soft-delete this deal?")){await api("softDeleteDeal",{deal_id:id});loadDeals();loadDashboard()}}async function restoreDeal(id){await api("restoreDeal",{deal_id:id});loadDeals();loadDashboard()}
function renderProducts(){const show=products.length?products:DEMO_PRODUCTS;$("productGrid").innerHTML=show.map(p=>`<div class="card product"><div class="photo"><img loading="lazy" src="${esc(p.image_url||'')}" alt="${esc(p.color||'')}"></div><div class="pb"><div class="code">${esc(p.item_code)}</div><b>${esc(p.color)}</b><div class="sub">${esc(p.product_name||'Small Foil Balloon Weight')} · MOQ ${Number(p.moq_pcs||97000).toLocaleString()} pcs</div>${admin()?`<div class="internal">Expected $${Number(p.expected_fob_usd||0).toFixed(6)} · Floor $${Number(p.floor_fob_usd||0).toFixed(6)}</div>`:''}<div class="rowactions"><button class="btn light sm" onclick="toggleProduct('${esc(p.product_id)}')">${selectedProducts.has(p.product_id)?'Selected':'Select for proposal'}</button>${can('can_manage_products')?`<button class="btn light sm" onclick='openProduct(${JSON.stringify(JSON.stringify(p))})'>Edit</button>`:''}</div></div></div>`).join('');$("pProducts").textContent=selectedProducts.size?[...selectedProducts].map(id=>products.find(p=>p.product_id===id)?.item_code||id).join(', '):'Select products from the Products tab.'}
async function loadProducts(render=true){if(!products.length)products=cacheGet("products")||DEMO_PRODUCTS;if(render)renderProducts();try{const r=await apiFast("listProducts",{include_deleted:$("showDeletedProducts")?.checked||false},2200);if(r.ok){products=r.products;cacheSet("products",products);if(render)renderProducts()}}catch{}return products}
function toggleProduct(id){selectedProducts.has(id)?selectedProducts.delete(id):selectedProducts.add(id);renderProducts()}
function openProduct(js){const p=js?JSON.parse(js):{};modal(p.product_id?"Edit product":"Add product",`<input id="mPid" type="hidden" value="${esc(p.product_id||"")}"><div class="grid2"><div><label>Item code *</label><input id="mPCode" value="${esc(p.item_code||"")}"></div><div><label>Color *</label><input id="mPColor" value="${esc(p.color||"")}"></div></div><label>Product name</label><input id="mPName" value="${esc(p.product_name||'Small Foil Balloon Weight')}"><div class="grid2"><div><label>MOQ pcs</label><input id="mPMoq" type="number" value="${esc(p.moq_pcs||97000)}"></div><div><label>Image URL</label><input id="mPImg" value="${esc(p.image_url||"")}"></div></div>${admin()?`<div class="grid2"><div><label>Expected FOB USD/pc</label><input id="mPExp" type="number" step="0.000001" value="${esc(p.expected_fob_usd||"")}"></div><div><label>Floor FOB USD/pc</label><input id="mPFloor" type="number" step="0.000001" value="${esc(p.floor_fob_usd||"")}"></div></div>`:""}<button class="btn o full" onclick="saveProduct()">Save product</button><div id="mMsg" class="msg"></div>`)}
async function saveProduct(){try{const r=await api("saveProduct",{product_id:$("mPid").value,item_code:$("mPCode").value,color:$("mPColor").value,product_name:$("mPName").value,moq_pcs:$("mPMoq").value,image_url:$("mPImg").value,expected_fob_usd:$("mPExp")?.value||"",floor_fob_usd:$("mPFloor")?.value||""});if(!r.ok)throw Error(r.error);closeModal();loadProducts();fillSelects()}catch(e){message("mMsg",e.message)}}
function fillProposalCustomer(){const c=customers.find(x=>x.customer_id===$("pCustomer").value);if(c&&!$("pContext").value)$("pContext").value=`${c.company_name} in ${c.country||"target market"} — validate annual volume, target colors, packaging and delivery window.`}
function fillQuoteCustomer(){const c=customers.find(x=>x.customer_id===$("qCustomer").value);if(c){const d=deals.find(x=>x.customer_id===c.customer_id&&String(x.active)!=="false");if(d)$("qDeal").value=d.deal_id}}
function renderProposal(){const c=customers.find(x=>x.customer_id===$("pCustomer").value);const ps=[...selectedProducts].map(id=>products.find(p=>p.product_id===id)).filter(Boolean);$("proposalPreview").innerHTML=`<div class="pvhead"><div class="brandrow"><img class="logo" src="https://newpefso.github.io/info/assets/brand/pefso-icon-square.png"><div><b>PEFSO VIETNAM</b><h1 style="margin:4px 0">Balloon Weight Proposal</h1></div></div></div><div class="pvbody"><h2>${esc(c?.company_name||"Buyer")}</h2><p>${esc($("pContext").value)}</p><h3>Recommended direction</h3><p>${esc($("pDirection").value)}</p><h3>Recommended collection</h3>${ps.map(p=>`<div class="item"><img src="${esc(p.image_url)}"><div><b>${esc(p.item_code)} · ${esc(p.color)}</b><div class="sub">${esc(p.product_name)} · MOQ ${Number(p.moq_pcs||0).toLocaleString()} pcs</div></div></div>`).join("")}<h3>Why PEFSO</h3><p>Vietnam production platform · seasonal product experience · buyer-spec OEM execution · material and supplier coordination · structured QC.</p><h3>Next step</h3><p>${esc($("pNext").value)}</p><div class="note">Final shade, specifications, mixed-SKU loading and commercial terms are subject to PEFSO confirmation and buyer-approved sample.</div></div>`}
async function saveProposal(){renderProposal();try{const r=await api("saveProposal",{customer_id:$("pCustomer").value,deal_id:$("pDeal").value,buyer_context:$("pContext").value,recommended_direction:$("pDirection").value,next_step:$("pNext").value,selected_product_ids:[...selectedProducts]});if(!r.ok)throw Error(r.error);message("proposalMsg","Proposal saved: "+r.proposal_id,true);loadDashboard()}catch(e){message("proposalMsg",e.message)}}
function renderQuote(){const c=customers.find(x=>x.customer_id===$("qCustomer").value),p=products.find(x=>x.product_id===$("qProduct").value),qty=Number($("qQty").value||0),pr=Number($("qPrice").value||0);$("quotePreview").innerHTML=`<div class="pvhead"><div class="brandrow"><img class="logo" src="https://newpefso.github.io/info/assets/brand/pefso-icon-square.png"><div><b>PEFSO CO., LTD.</b><h1 style="margin:4px 0">QUOTATION</h1><div>PENDING ADMIN APPROVAL</div></div></div></div><div class="pvbody"><b>To:</b> ${esc(c?.company_name||"")}<br><span class="sub">${esc(c?.country||"")}</span><table><tr><th>Item</th><th>Color</th><th>Qty</th><th>FOB USD/pc</th><th>Total</th></tr><tr><td>${esc(p?.item_code||"")}</td><td>${esc(p?.color||"")}</td><td>${qty.toLocaleString()}</td><td>${pr?pr.toFixed(6):"Pending"}</td><td>${pr?"$"+(qty*pr).toLocaleString(undefined,{maximumFractionDigits:2}):"Pending"}</td></tr></table><p><b>Incoterm:</b> ${esc($("qTerm").value)}<br><b>Port:</b> ${esc($("qPort").value)}<br><b>Payment:</b> ${esc($("qPayment").value)}<br><b>Lead time:</b> ${esc($("qLead").value)}</p><div class="note">Official only after PEFSO Admin approval.</div></div>`}
async function saveQuote(){renderQuote();try{const r=await api("saveQuotation",{customer_id:$("qCustomer").value,deal_id:$("qDeal").value,product_id:$("qProduct").value,quantity:$("qQty").value,requested_unit_price:$("qPrice").value,destination_port:$("qPort").value,incoterm:$("qTerm").value,validity_days:$("qValidity").value,payment_terms:$("qPayment").value,lead_time:$("qLead").value});if(!r.ok)throw Error(r.error);message("quoteMsg","Quotation saved: "+r.quotation_no+" V"+r.version,true);loadQuotes();loadDashboard()}catch(e){message("quoteMsg",e.message)}}
function renderDemoQuotes(){$("quotesWrap").innerHTML='<table><tr><th>No.</th><th>Buyer</th><th>Item</th><th>Qty</th><th>Price</th><th>Status</th></tr>'+DEMO_QUOTES.map(q=>`<tr><td>${q.quotation_no} V${q.version}</td><td>${q.buyer_company}</td><td>${q.item_code} · ${q.color}</td><td>${Number(q.quantity).toLocaleString()}</td><td>${Number(q.approved_unit_price||q.requested_unit_price).toFixed(6)}</td><td><span class="badge">${q.status}</span></td></tr>`).join('')+'</table>'}
async function loadQuotes(){renderDemoQuotes();try{const r=await apiFast("listQuotations",{},2200);if(r.ok)$("quotesWrap").innerHTML='<table><tr><th>No.</th><th>Buyer</th><th>Item</th><th>Qty</th><th>Price</th><th>Status</th><th></th></tr>'+r.quotations.map(q=>`<tr><td>${esc(q.quotation_no)} V${esc(q.version)}</td><td>${esc(q.buyer_company)}</td><td>${esc(q.item_code)} · ${esc(q.color)}</td><td>${Number(q.quantity||0).toLocaleString()}</td><td>${q.approved_unit_price?Number(q.approved_unit_price).toFixed(6):Number(q.requested_unit_price||0).toFixed(6)}</td><td><span class="badge">${esc(q.status)}</span></td><td>${admin()&&q.status!=="Approved"?`<button class="btn o sm" onclick="approveQuote('${esc(q.quotation_id)}')">Approve</button>`:""}</td></tr>`).join("")+'</table>'}catch{}}
async function approveQuote(id){const price=prompt("Approved unit price USD/pc");if(price===null)return;const r=await api("approveQuotation",{quotation_id:id,approved_unit_price:price});if(!r.ok)alert(r.error);loadQuotes();loadDashboard()}
async function saveActivity(){try{const r=await api("logActivity",{customer_id:$("aCustomer").value,deal_id:$("aDeal").value,activity_type:$("aType").value,channel:$("aChannel").value,summary:$("aSummary").value,next_action:$("aNext").value,next_action_date:$("aDate").value,meaningful:$("aMeaningful").checked});if(!r.ok)throw Error(r.error);message("activityMsg","Activity logged.",true);$("aSummary").value="";loadActivities();loadDashboard()}catch(e){message("activityMsg",e.message)}}
function renderDemoActivities(){$("activityWrap").innerHTML='<table><tr><th>Date</th><th>User</th><th>Activity</th><th>Summary</th></tr>'+scopedDemo(DEMO_ACTIVITIES).map(a=>`<tr><td>${a.timestamp}</td><td>${a.user_id}</td><td>${a.activity_type}<div class="sub">${a.channel}</div></td><td>${a.summary}</td></tr>`).join('')+'</table>'}
async function loadActivities(){renderDemoActivities();try{const r=await apiFast("listActivities",{},2200);if(r.ok)$("activityWrap").innerHTML='<table><tr><th>Date</th><th>User</th><th>Activity</th><th>Summary</th></tr>'+r.activities.slice(0,30).map(a=>`<tr><td>${esc(String(a.timestamp).slice(0,10))}</td><td>${esc(a.user_id)}</td><td>${esc(a.activity_type)}<div class="sub">${esc(a.channel)}</div></td><td>${esc(a.summary)}</td></tr>`).join("")+'</table>'}catch{}}
async function loadUsers(){try{const r=await apiFast("listUsers",{},2200);if(!r.ok)throw Error(r.error);$("usersWrap").innerHTML='<table><tr><th>ID</th><th>Role</th><th>Name</th><th>Visible PIN</th><th>Status</th><th></th></tr>'+r.users.map(u=>`<tr><td><b>${esc(u.user_id)}</b></td><td>${esc(u.role)}</td><td>${esc(u.display_name)}</td><td><b>${esc(u.visible_pin||"")}</b></td><td>${String(u.active)==="false"?"Inactive":"Active"}</td><td><div class="rowactions"><button class="btn light sm" onclick='openUser(${JSON.stringify(JSON.stringify(u))})'>Edit</button><button class="btn light sm" onclick="resetPin('${esc(u.user_id)}')">Change PIN</button><button class="btn red sm" onclick="toggleUserActive('${esc(u.user_id)}',${String(u.active)==="false"})">${String(u.active)==="false"?"Activate":"Deactivate"}</button></div></td></tr>`).join("")+'</table>'}catch(e){$("usersWrap").textContent=e.message}}
function openUser(js){const u=js?JSON.parse(js):{};modal(u.user_id?"Edit user":"Add user",`<input id="mUOld" type="hidden" value="${esc(u.user_id||"")}"><label>User ID *</label><input id="mUid" value="${esc(u.user_id||"")}"><label>Display name</label><input id="mUName" value="${esc(u.display_name||"")}"><label>Role</label><select id="mURole">${["admin","staff","collaborator"].map(x=>`<option ${u.role===x?"selected":""}>${x}</option>`).join("")}</select>${u.user_id?"":'<label>8-digit PIN *</label><input id="mUPin" maxlength="8">'}<button class="btn o full" onclick="saveUser()">Save user</button><div id="mMsg" class="msg"></div>`)}
async function saveUser(){try{const r=await api("saveUser",{original_user_id:$("mUOld").value,user_id:$("mUid").value,display_name:$("mUName").value,role:$("mURole").value,pin:$("mUPin")?.value||""});if(!r.ok)throw Error(r.error);closeModal();loadUsers()}catch(e){message("mMsg",e.message)}}
async function resetPin(id){const pin=prompt("New 8-digit PIN");if(pin===null)return;const r=await api("resetPin",{user_id:id,new_pin:pin});if(!r.ok)alert(r.error);loadUsers()}async function toggleUserActive(id,active){const r=await api("setUserActive",{user_id:id,active});if(!r.ok)alert(r.error);loadUsers()}
async function loadAudit(){try{const r=await apiFast("listAudit",{},2200);if(!r.ok)throw Error(r.error);$("auditWrap").innerHTML='<table><tr><th>Time</th><th>User</th><th>Action</th><th>Entity</th><th>Target</th><th>Soft delete</th></tr>'+r.events.slice(0,100).map(a=>`<tr><td>${esc(a.timestamp)}</td><td>${esc(a.actor_user_id)}</td><td>${esc(a.action)}</td><td>${esc(a.entity_type||"")}</td><td>${esc(a.target_id||"")}</td><td>${esc(a.soft_deleted||"")}</td></tr>`).join("")+'</table>'}catch(e){$("auditWrap").textContent=e.message}}
async function saveOwn(){try{const r=await api("changeOwnCredentials",{new_user_id:$("ownId").value,current_pin:$("ownOld").value,new_pin:$("ownNew").value});if(!r.ok)throw Error(r.error);localStorage.removeItem("pefso_token");location.reload()}catch(e){message("ownMsg",e.message)}}
function printSection(id){document.querySelectorAll(".section").forEach(s=>s.classList.remove("printme"));$(id).classList.add("printme");window.print();$(id).classList.remove("printme")}
boot();