const API="https://script.google.com/macros/s/AKfycbxO5nf0N0IF3YIPCLREDRLFrhIU9bWhadfrjhtLb5vT8ZRFiv_ffkZQRO-QL6VqASMsHA/exec";
let token=localStorage.getItem("pefso_token")||"", me=null, customers=[],deals=[],products=[],selectedProducts=new Set();
const $=id=>document.getElementById(id), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(action,p={}){const r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,token,...p})});return r.json()}
function message(id,t,ok=false){const e=$(id);e.textContent=t||"";e.className="msg "+(ok?"ok":"err")}
function can(k){return me&&me.permissions&&(me.permissions[k]===true||String(me.permissions[k])==="true")}
function admin(){return me&&me.role==="admin"} function staff(){return me&&me.role==="staff"}
function closeModal(){$("modal").classList.add("hidden")} function modal(title,body){$("modalTitle").textContent=title;$("modalBody").innerHTML=body;$("modal").classList.remove("hidden")}
function go(tab){document.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));document.querySelectorAll(".section").forEach(s=>s.classList.toggle("active",s.id===tab));if(tab==="dashboard")loadDashboard();if(tab==="customers")loadCustomers();if(tab==="deals")loadDeals();if(tab==="products")loadProducts();if(tab==="quotation")loadQuotes();if(tab==="activity")loadActivities();if(tab==="users")loadUsers();if(tab==="audit")loadAudit()}
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>go(b.dataset.tab));
$("loginBtn").onclick=async()=>{const pin=$("loginPin").value.trim();if(!/^\d{8}$/.test(pin))return message("loginMsg","PIN must be exactly 8 digits");try{const r=await api("login",{user_id:$("loginId").value.trim(),pin});if(!r.ok)throw Error(r.error);token=r.token;localStorage.setItem("pefso_token",token);showApp(r.user)}catch(e){message("loginMsg",e.message)}}
$("logoutBtn").onclick=async()=>{try{await api("logout")}catch{}localStorage.removeItem("pefso_token");location.reload()}
async function boot(){if(!token)return;try{const r=await api("me");if(r.ok)showApp(r.user)}catch{}}
async function showApp(u){me=u;$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("who").textContent=(u.display_name||u.user_id)+" · "+u.role;$("ownId").value=u.user_id;$("usersTab").classList.toggle("hidden",!can("can_manage_users"));$("auditTab").classList.toggle("hidden",!admin());$("addProductBtn").classList.toggle("hidden",!can("can_manage_products"));await refreshCore();loadDashboard()}
async function refreshCore(){await Promise.all([loadCustomers(false),loadDeals(false),loadProducts(false)]);fillSelects()}
function fillSelects(){const cust=customers.filter(x=>x.active!==false&&String(x.active)!=="false");const co='<option value="">Select…</option>'+cust.map(c=>`<option value="${esc(c.customer_id)}">${esc(c.company_name)}</option>`).join("");["pCustomer","qCustomer","aCustomer"].forEach(id=>$(id).innerHTML=co);const dl='<option value="">Select…</option>'+deals.filter(d=>d.active!==false&&String(d.active)!=="false").map(d=>`<option value="${esc(d.deal_id)}">${esc(d.deal_name)}</option>`).join("");["pDeal","qDeal","aDeal"].forEach(id=>$(id).innerHTML=dl);$("qProduct").innerHTML='<option value="">Select…</option>'+products.filter(p=>String(p.status).toLowerCase()!=="deleted").map(p=>`<option value="${esc(p.product_id)}">${esc(p.item_code)} · ${esc(p.color)}</option>`).join("")}
async function loadDashboard(){try{const r=await api("dashboard");if(!r.ok)throw Error(r.error);$("kCustomers").textContent=r.kpi.customers;$("kDeals").textContent=r.kpi.open_deals;$("kPending").textContent=r.kpi.pending_quotes;$("kActivities").textContent=r.kpi.activities_7d;$("teamWrap").innerHTML='<table><tr><th>User</th><th>Activities 7d</th><th>Meaningful</th><th>Customers</th><th>Open deals</th><th>Proposals</th><th>Quotes</th><th>Won</th></tr>'+r.team.map(x=>`<tr><td><b>${esc(x.user_id)}</b></td><td>${x.activities_7d}</td><td>${x.meaningful_7d}</td><td>${x.customers}</td><td>${x.open_deals}</td><td>${x.proposals}</td><td>${x.quotations}</td><td>${x.won}</td></tr>`).join("")+'</table>';$("pipelineWrap").innerHTML='<div class="grid4">'+Object.entries(r.pipeline).map(([k,v])=>`<div class="card kpi"><span>${esc(k)}</span><b>${v}</b></div>`).join("")+'</div>'}catch(e){$("teamWrap").textContent=e.message}}
async function loadCustomers(render=true){try{const r=await api("listCustomers",{include_deleted:$("showDeletedCustomers")?.checked||false});if(!r.ok)throw Error(r.error);customers=r.customers;if(render){$("customersWrap").innerHTML='<table><tr><th>Company</th><th>Country</th><th>Contact</th><th>Owner</th><th>Status</th><th></th></tr>'+customers.map(c=>`<tr><td><b>${esc(c.company_name)}</b><div class="sub">${esc(c.domain||c.website||"")}</div></td><td>${esc(c.country||"")}</td><td>${esc(c.contact_name||"")}<div class="sub">${esc(c.contact_email||"")}</div></td><td>${esc(c.owner_user_id||"")}</td><td><span class="badge">${String(c.active)==="false"?"Deleted":esc(c.account_status||"Active")}</span></td><td><div class="rowactions"><button class="btn light sm" onclick='openCustomer(${JSON.stringify(JSON.stringify(c))})'>Edit</button>${String(c.active)==="false"?`<button class="btn sm" onclick="restoreCustomer('${esc(c.customer_id)}')">Restore</button>`:`<button class="btn red sm" onclick="deleteCustomer('${esc(c.customer_id)}')">Delete</button>`}</div></td></tr>`).join("")+'</table>'}return customers}catch(e){if(render)$("customersWrap").textContent=e.message;return[]}}
function openCustomer(js){const c=js?JSON.parse(js):{};const owners=(admin()||staff())?'<label>Owner</label><select id="mOwner">'+["staff","ctv","ctv1","ctv2"].map(x=>`<option ${c.owner_user_id===x?"selected":""}>${x}</option>`).join("")+'</select>':"";modal(c.customer_id?"Edit customer":"Add customer",`<input id="mCid" type="hidden" value="${esc(c.customer_id||"")}"><label>Company name *</label><input id="mCompany" value="${esc(c.company_name||"")}"><div class="grid2"><div><label>Website</label><input id="mWeb" value="${esc(c.website||"")}"></div><div><label>Country</label><input id="mCountry" value="${esc(c.country||"")}"></div></div><div class="grid2"><div><label>Contact name</label><input id="mContact" value="${esc(c.contact_name||"")}"></div><div><label>Contact email</label><input id="mEmail" value="${esc(c.contact_email||"")}"></div></div>${owners}<div class="note">Duplicate control uses website/email domain first, then company name + country.</div><button class="btn o full" onclick="saveCustomer()">Save customer</button><div id="mMsg" class="msg"></div>`)}
async function saveCustomer(){try{const r=await api("saveCustomer",{customer_id:$("mCid").value,company_name:$("mCompany").value,website:$("mWeb").value,country:$("mCountry").value,contact_name:$("mContact").value,contact_email:$("mEmail").value,owner_user_id:$("mOwner")?.value||me.user_id});if(!r.ok)throw Error(r.error);closeModal();await loadCustomers();fillSelects();loadDashboard()}catch(e){message("mMsg",e.message)}}
async function deleteCustomer(id){if(!confirm("Soft-delete this customer? The backend history will be retained."))return;await api("softDeleteCustomer",{customer_id:id});loadCustomers();loadDashboard()} async function restoreCustomer(id){await api("restoreCustomer",{customer_id:id});loadCustomers();loadDashboard()}