function showGuide(){
  const role=(me&&me.role)||'collaborator';
  const common=`<div class="note"><b>Core rule</b><br>Keep every real sales step in PEFSO Sales: customer → deal → activity → proposal / quotation → won or lost.</div>`;
  const guides={
    admin:`<div class="ey">ADMIN GUIDE</div><h2>Control the sales system</h2>${common}<ol><li><b>Dashboard:</b> check team effort, open deals and pending quotations.</li><li><b>Customers:</b> resolve duplicate or ownership issues. One customer has one active owner.</li><li><b>Deals:</b> review movement, overdue next actions, Lost reasons and Won requests.</li><li><b>Quotation:</b> approve the official selling price. Keep version history; never overwrite an older quote.</li><li><b>Users:</b> add users, assign roles, reset PINs or deactivate access.</li><li><b>Audit:</b> use the log when a record was changed, deleted or restored.</li></ol><div class="note"><b>Scope:</b> V1 stops at sales outcome and commission status. Production, shipment, receivables and accounting stay outside this app.</div>`,
    staff:`<div class="ey">STAFF GUIDE</div><h2>Sell + maintain sales data</h2>${common}<ol><li>Add or update <b>Products</b> when approved product information changes.</li><li>Create <b>Customers</b> with only company, website/email domain, country and main contact.</li><li>Create a <b>Deal</b>; always keep Stage + Next Action + Next Action Date current.</li><li>Log meaningful <b>Activity</b> after emails, calls, meetings, samples or negotiation.</li><li>Create <b>Proposal</b> and submit <b>Quotation</b> for Admin approval.</li><li>When buyer confirms an order, use <b>Request Won</b>. Admin confirms final quantity/price.</li></ol>`,
    collaborator:`<div class="ey">COLLABORATOR GUIDE</div><h2>Work your assigned accounts</h2>${common}<ol><li>You only work customers assigned to you. Search/check before adding a new company.</li><li>For every active deal, keep <b>Next Action</b> and date updated.</li><li>Log meaningful activity after buyer contact. This keeps lead protection active.</li><li>Use <b>Products</b> to select approved items; internal floor price is not visible.</li><li>Create a <b>Proposal</b>, then a <b>Quotation Request</b>. Admin approves official pricing.</li><li>When buyer confirms the order, use <b>Request Won</b>. Do not mark Won yourself.</li><li>If lost, choose a <b>Lost Reason</b> so PEFSO can learn from the deal.</li></ol><div class="note"><b>Lead protection:</b> 90 days with meaningful activity. A 30-day inactivity warning means the account needs follow-up.</div>`
  };
  modal('Quick guide',guides[role]||guides.collaborator);
}

function openDeal(js){
  const d=js?JSON.parse(js):{};
  const opts=customers.filter(c=>String(c.active)!=="false").map(c=>`<option value="${esc(c.customer_id)}" ${d.customer_id===c.customer_id?"selected":""}>${esc(c.company_name)}</option>`).join("");
  const stages=me&&me.role==='admin'?["Lead","Qualified","Proposal","Sample","Quotation","Negotiation","Won","Lost","On hold"]:["Lead","Qualified","Proposal","Sample","Quotation","Negotiation","Lost","On hold"];
  modal(d.deal_id?"Edit deal":"Add deal",`<input id="mDid" type="hidden" value="${esc(d.deal_id||"")}"><label>Customer *</label><select id="mDCustomer">${opts}</select><label>Deal name *</label><input id="mDName" value="${esc(d.deal_name||"")}"><div class="grid2"><div><label>Stage</label><select id="mDStage">${stages.map(x=>`<option ${d.stage===x?"selected":""}>${x}</option>`).join("")}</select></div><div><label>Estimated quantity</label><input id="mDQty" type="number" value="${esc(d.estimated_qty||97000)}"></div></div><div class="grid2"><div><label>Target price USD/pc</label><input id="mDTarget" type="number" step="0.000001" value="${esc(d.customer_target_price_usd||"")}"></div><div><label>Destination port</label><input id="mDPort" value="${esc(d.destination_port||"")}"></div></div><label>Next action</label><input id="mDNext" value="${esc(d.next_action||"")}"><label>Next action date</label><input id="mDDate" type="date" value="${esc(String(d.next_action_date||"").slice(0,10))}"><label>Lost reason <span class="sub">(required when Lost)</span></label><select id="mDLost"><option></option>${["Price","MOQ","Quality/spec","Lead time","Payment terms","Competitor","Buyer inactive","Timing/budget","Other"].map(x=>`<option ${d.lost_reason===x?"selected":""}>${x}</option>`).join("")}</select><div class="rowactions" style="margin-top:12px"><button class="btn o" onclick="saveDealEnhanced()">Save deal</button>${d.deal_id&&me&&me.role!=="admin"?`<button class="btn light" onclick="requestWon('${esc(d.deal_id)}')">Request Won</button>`:""}${d.deal_id&&me&&me.role==="admin"&&String(d.request_won).toLowerCase()==="true"?`<button class="btn" onclick="confirmWon('${esc(d.deal_id)}')">Confirm Won</button>`:""}</div><div id="mMsg" class="msg"></div>`);
}

async function saveDealEnhanced(){
  try{
    if($("mDStage").value==="Lost"&&!$("mDLost").value) throw Error("Lost reason is required.");
    const r=await api("saveDeal",{deal_id:$("mDid").value,customer_id:$("mDCustomer").value,deal_name:$("mDName").value,stage:$("mDStage").value,estimated_qty:$("mDQty").value,customer_target_price_usd:$("mDTarget").value,destination_port:$("mDPort").value,next_action:$("mDNext").value,next_action_date:$("mDDate").value,lost_reason:$("mDLost").value});
    if(!r.ok)throw Error(r.error);closeModal();await loadDeals();fillSelects();loadDashboard();
  }catch(e){message("mMsg",e.message)}
}
async function requestWon(id){try{const r=await api("requestWon",{deal_id:id});if(!r.ok)throw Error(r.error);closeModal();await loadDeals();loadDashboard()}catch(e){message("mMsg",e.message||"Request Won requires the current backend version.")}}
async function confirmWon(id){const price=prompt("Final selling price (USD/pc)");if(price===null)return;const qty=prompt("Final quantity (pcs)");if(qty===null)return;try{const r=await api("confirmWon",{deal_id:id,final_selling_price:Number(price),final_qty:Number(qty)});if(!r.ok)throw Error(r.error);closeModal();await loadDeals();loadDashboard()}catch(e){message("mMsg",e.message||"Confirm Won requires the current backend version.")}}

(()=>{const s=document.createElement('script');s.src='phase2.js?v=8';document.body.appendChild(s)})();