const SPREADSHEET_ID = "1o7OXEp7FHMrJ2TPqmWXH6BQM25nLqxxdC0J2l6f2O_c";
const USERS_SHEET = "USERS";
const SESSIONS_SHEET = "SESSIONS";
const AUDIT_SHEET = "AUDIT_LOG";
const ATTEMPTS_SHEET = "LOGIN_ATTEMPTS";
const PRODUCTS_SHEET = "PRODUCT_MASTER";
const PROPOSALS_SHEET = "PROPOSALS";
const QUOTATIONS_SHEET = "QUOTATIONS";
function doGet(e){return handle_(e&&e.parameter?e.parameter:{});}function doPost(e){let p={};try{p=JSON.parse((e&&e.postData&&e.postData.contents)||"{}");}catch(err){}return handle_(p);}
function handle_(p){try{ensureSchema_();const a=String(p.action||"");if(a==="health")return out_({ok:true,service:"PEFSO Sales",version:"3.0"});if(a==="login")return out_(login_(p));if(a==="me")return out_(me_(p));if(a==="logout")return out_(logout_(p));if(a==="listUsers")return out_(listUsers_(p));if(a==="saveUser")return out_(saveUser_(p));if(a==="resetPin")return out_(resetPin_(p));if(a==="changeOwnCredentials")return out_(changeOwnCredentials_(p));if(a==="setUserActive")return out_(setUserActive_(p));if(a==="listProducts")return out_(listProducts_(p));if(a==="saveProposal")return out_(saveProposal_(p));if(a==="listProposals")return out_(listProposals_(p));if(a==="saveQuotation")return out_(saveQuotation_(p));if(a==="listQuotations")return out_(listQuotations_(p));if(a==="approveQuotation")return out_(approveQuotation_(p));return out_({ok:false,error:"Unknown action"});}catch(err){return out_({ok:false,error:String(err&&err.message?err.message:err)});}}
function out_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}function ss_(){return SpreadsheetApp.openById(SPREADSHEET_ID);}function sh_(n){return ss_().getSheetByName(n);}function nowIso_(){return new Date().toISOString();}
function ensureSchema_(){const s=sh_(USERS_SHEET);if(!s)throw new Error("USERS sheet not found");if(String(s.getRange(3,15).getValue()||"")!=="hash_version")s.getRange(3,15).setValue("hash_version");[PRODUCTS_SHEET,PROPOSALS_SHEET,QUOTATIONS_SHEET].forEach(n=>{if(!sh_(n))throw new Error(n+" sheet not found");});}
function ensurePepper_(){const p=PropertiesService.getScriptProperties();let x=p.getProperty("PEFSO_AUTH_PEPPER");if(!x){x=Utilities.getUuid()+Utilities.getUuid()+Utilities.getUuid();p.setProperty("PEFSO_AUTH_PEPPER",x);}return x;}function hex_(b){return b.map(x=>{let v=(x<0?x+256:x).toString(16);return v.length===1?"0"+v:v;}).join("");}function sha256_(t){return hex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,t,Utilities.Charset.UTF_8));}function hashV1_(pin,salt){return sha256_(String(salt)+":"+String(pin));}function hashV2_(pin,salt){return sha256_(ensurePepper_()+":"+String(salt)+":"+String(pin));}function randomSalt_(){return Utilities.getUuid().replace(/-/g,"")+Utilities.getUuid().replace(/-/g,"");}function randomToken_(){return sha256_(Utilities.getUuid()+":"+Utilities.getUuid()+":"+Date.now());}function validPin_(p){return /^\d{8}$/.test(String(p||""));}
function rowsAsObjects_(sheet,headerRow){const lr=sheet.getLastRow(),lc=sheet.getLastColumn();if(lr<headerRow)return {headers:[],rows:[]};const v=sheet.getRange(headerRow,1,lr-headerRow+1,lc).getValues(),h=v[0].map(String);return {headers:h,rows:v.slice(1).map((r,i)=>{let o={_row:headerRow+1+i};h.forEach((k,j)=>{if(k)o[k]=r[j];});return o;}).filter(o=>h.some(k=>String(o[k]??"").trim()!==""))};}
function findUser_(id){const w=String(id||"").trim().toLowerCase();return rowsAsObjects_(sh_(USERS_SHEET),3).rows.find(u=>String(u.user_id||"").trim().toLowerCase()===w)||null;}
function login_(p){const id=String(p.user_id||"").trim(),pin=String(p.pin||"");if(!id||!validPin_(pin))return {ok:false,error:"ID hoặc PIN không hợp lệ"};const u=findUser_(id);if(!u||String(u.active).toLowerCase()!=="true"){logAttempt_(id,false,"user_not_found_or_inactive");return {ok:false,error:"ID hoặc PIN không đúng"};}const ver=String(u.hash_version||"v1_sha256_salt"),cand=ver==="v2_pepper_sha256"?hashV2_(pin,u.salt):hashV1_(pin,u.salt);if(cand!==String(u.pin_hash)){logAttempt_(id,false,"bad_pin");return {ok:false,error:"ID hoặc PIN không đúng"};}if(ver!=="v2_pepper_sha256"){const salt=randomSalt_();updateUserHash_(u._row,pin,salt);u.salt=salt;u.hash_version="v2_pepper_sha256";}const token=randomToken_(),issued=new Date(),expires=new Date(issued.getTime()+8*60*60*1000);sh_(SESSIONS_SHEET).appendRow([sha256_(token),u.user_id,u.role,issued,expires,issued,true,"","","login"]);logAttempt_(id,true,"");audit_(u.user_id,"LOGIN",u.user_id,"success","");return {ok:true,token,user:safeUser_(u)};}
function updateUserHash_(row,pin,salt){const s=sh_(USERS_SHEET);s.getRange(row,4).setValue(hashV2_(pin,salt));s.getRange(row,5).setValue(salt);s.getRange(row,13).setValue(nowIso_());s.getRange(row,15).setValue("v2_pepper_sha256");}
function sessionUser_(token){if(!token)return null;const h=sha256_(String(token)),s=sh_(SESSIONS_SHEET),d=s.getDataRange().getValues();if(d.length<4)return null;const heads=d[2].map(String);for(let i=3;i<d.length;i++){let o={};heads.forEach((k,j)=>{if(k)o[k]=d[i][j]});if(String(o.session_token_hash)===h&&String(o.active).toLowerCase()==="true"&&new Date(o.expires_at).getTime()>Date.now()){const u=findUser_(o.user_id);if(!u||String(u.active).toLowerCase()!=="true")return null;s.getRange(i+1,6).setValue(new Date());return u;}}return null;}function requireUser_(p){const u=sessionUser_(p.token);if(!u)throw new Error("Unauthorized");return u;}function requireAdmin_(p){const u=requireUser_(p);if(String(u.can_manage_users).toLowerCase()!=="true")throw new Error("Forbidden");return u;}function safeUser_(u){return {user_id:u.user_id,role:u.role,display_name:u.display_name,active:u.active,permissions:{can_manage_users:u.can_manage_users,can_manage_products:u.can_manage_products,can_approve_quotation:u.can_approve_quotation,can_see_all_customers:u.can_see_all_customers,can_manage_prices:u.can_manage_prices}};}function me_(p){return {ok:true,user:safeUser_(requireUser_(p))};}
function logout_(p){if(!p.token)return {ok:true};const h=sha256_(String(p.token)),s=sh_(SESSIONS_SHEET),d=s.getDataRange().getValues();for(let i=3;i<d.length;i++){if(String(d[i][0])===h){s.getRange(i+1,7).setValue(false);break;}}return {ok:true};}
function listUsers_(p){requireAdmin_(p);return {ok:true,users:rowsAsObjects_(sh_(USERS_SHEET),3).rows.map(safeUser_)}}function roleDefaults_(r){if(r==="admin")return {can_manage_users:true,can_manage_products:true,can_approve_quotation:true,can_see_all_customers:true,can_manage_prices:true};if(r==="staff")return {can_manage_users:false,can_manage_products:true,can_approve_quotation:false,can_see_all_customers:true,can_manage_prices:false};return {can_manage_users:false,can_manage_products:false,can_approve_quotation:false,can_see_all_customers:false,can_manage_prices:false};}
function saveUser_(p){const actor=requireAdmin_(p),old=String(p.original_user_id||"").trim(),id=String(p.user_id||"").trim(),role=String(p.role||"").trim(),name=String(p.display_name||"").trim();if(!/^[A-Za-z0-9._-]{3,40}$/.test(id))throw new Error("User ID format invalid");if(!["admin","staff","collaborator"].includes(role))throw new Error("Role invalid");const s=sh_(USERS_SHEET),same=old?findUser_(old):null,clash=findUser_(id);if(clash&&(!same||clash._row!==same._row))throw new Error("User ID already exists");const f=roleDefaults_(role);if(same){s.getRange(same._row,1,1,3).setValues([[id,role,name||id]]);s.getRange(same._row,6,1,6).setValues([[p.active!==false,f.can_manage_users,f.can_manage_products,f.can_approve_quotation,f.can_see_all_customers,f.can_manage_prices]]);s.getRange(same._row,13).setValue(nowIso_());audit_(actor.user_id,"UPDATE_USER",id,"success","");}else{if(!validPin_(p.pin))throw new Error("New user requires an 8-digit PIN");const salt=randomSalt_();s.appendRow([id,role,name||id,hashV2_(p.pin,salt),salt,true,f.can_manage_users,f.can_manage_products,f.can_approve_quotation,f.can_see_all_customers,f.can_manage_prices,nowIso_(),nowIso_(),"Created by "+actor.user_id,"v2_pepper_sha256"]);audit_(actor.user_id,"CREATE_USER",id,"success","");}return {ok:true};}
function resetPin_(p){const a=requireAdmin_(p),u=findUser_(p.user_id);if(!u)throw new Error("User not found");if(!validPin_(p.new_pin))throw new Error("PIN must contain exactly 8 digits");updateUserHash_(u._row,p.new_pin,randomSalt_());invalidateUserSessions_(u.user_id);audit_(a.user_id,"RESET_PIN",u.user_id,"success","");return {ok:true};}function changeOwnCredentials_(p){const u=requireUser_(p),oldPin=String(p.current_pin||""),newId=String(p.new_user_id||u.user_id).trim(),newPin=String(p.new_pin||"");if(!validPin_(oldPin))throw new Error("Current PIN required");const live=findUser_(u.user_id),ver=String(live.hash_version||"v1_sha256_salt"),check=ver==="v2_pepper_sha256"?hashV2_(oldPin,live.salt):hashV1_(oldPin,live.salt);if(check!==String(live.pin_hash))throw new Error("Current PIN incorrect");if(newId!==String(live.user_id)){if(findUser_(newId))throw new Error("New user ID already exists");if(!/^[A-Za-z0-9._-]{3,40}$/.test(newId))throw new Error("User ID format invalid");sh_(USERS_SHEET).getRange(live._row,1).setValue(newId);}if(newPin){if(!validPin_(newPin))throw new Error("New PIN must contain exactly 8 digits");updateUserHash_(live._row,newPin,randomSalt_());}else sh_(USERS_SHEET).getRange(live._row,13).setValue(nowIso_());invalidateUserSessions_(u.user_id);audit_(u.user_id,"CHANGE_OWN_CREDENTIALS",newId,"success","");return {ok:true,relogin:true,new_user_id:newId};}
function setUserActive_(p){const a=requireAdmin_(p),u=findUser_(p.user_id);if(!u)throw new Error("User not found");if(String(u.user_id)===String(a.user_id)&&p.active===false)throw new Error("Admin cannot deactivate current account");sh_(USERS_SHEET).getRange(u._row,6).setValue(!!p.active);sh_(USERS_SHEET).getRange(u._row,13).setValue(nowIso_());if(!p.active)invalidateUserSessions_(u.user_id);audit_(a.user_id,p.active?"ACTIVATE_USER":"DEACTIVATE_USER",u.user_id,"success","");return {ok:true};}function invalidateUserSessions_(id){const s=sh_(SESSIONS_SHEET),d=s.getDataRange().getValues();for(let i=3;i<d.length;i++)if(String(d[i][1])===String(id)&&String(d[i][6]).toLowerCase()==="true")s.getRange(i+1,7).setValue(false);}
function listProducts_(p){const u=requireUser_(p),rows=rowsAsObjects_(sh_(PRODUCTS_SHEET),3).rows.filter(x=>String(x.status||"").toLowerCase()==="active"),admin=String(u.role)==="admin",staff=String(u.role)==="staff";return {ok:true,products:rows.map(x=>{let o={product_id:x.product_id,item_code:x.item_code,product_name:x.product_name,color:x.color,total_height_in:x.total_height_in,body_height_in:x.body_height_in,total_width_in:x.total_width_in,ring_tie_length_in:x.ring_tie_length_in,bottom_label_diameter_in:x.bottom_label_diameter_in,core:x.core,outer_finish:x.outer_finish,construction:x.construction,moq_pcs:x.moq_pcs,price_basis:x.price_basis,image_url:x.image_url,status:x.status};if(admin){o.floor_fob_usd=x.floor_fob_usd;o.expected_fob_usd=x.expected_fob_usd;}else if(staff)o.expected_fob_usd=x.expected_fob_usd;return o;})};}
function saveProposal_(p){const u=requireUser_(p);if(!String(p.buyer_company||"").trim())throw new Error("Buyer company required");const id="PR-"+Utilities.formatDate(new Date(),"Asia/Bangkok","yyyyMMdd-HHmmss")+"-"+String(Math.floor(Math.random()*900)+100);sh_(PROPOSALS_SHEET).appendRow([id,new Date(),u.user_id,p.buyer_company||"",p.buyer_contact||"",p.buyer_email||"",p.country||"",p.selected_item_codes||"",p.buyer_context||"",p.recommended_direction||"",p.customization||"",p.next_step||"","Draft",p.html_snapshot||"",p.notes||""]);audit_(u.user_id,"SAVE_PROPOSAL",id,"success",p.buyer_company||"");return {ok:true,proposal_id:id,status:"Draft"};}
function listProposals_(p){const u=requireUser_(p),rows=rowsAsObjects_(sh_(PROPOSALS_SHEET),3).rows;return {ok:true,proposals:(u.role==="admin"||u.role==="staff"?rows:rows.filter(x=>String(x.created_by)===String(u.user_id))).map(x=>{delete x.html_snapshot;return x;})};}
function nextQuotationNo_(){const y=Utilities.formatDate(new Date(),"Asia/Bangkok","yyyy"),rows=rowsAsObjects_(sh_(QUOTATIONS_SHEET),3).rows;let n=1;rows.forEach(r=>{let m=String(r.quotation_no||"").match(/^QT-(\d{4})-(\d+)$/);if(m&&m[1]===y)n=Math.max(n,Number(m[2])+1)});return "QT-"+y+"-"+String(n).padStart(4,"0");}
function saveQuotation_(p){const u=requireUser_(p);if(!String(p.buyer_company||"").trim())throw new Error("Buyer company required");if(!String(p.item_code||"").trim())throw new Error("Item code required");const qno=nextQuotationNo_(),id=qno+"-V1",qty=Number(p.quantity||0),req=Number(p.requested_unit_price||0),approved=(u.role==="admin"?Number(p.approved_unit_price||0):0),status=approved>0?"Approved":"Pending Approval",price=approved||req,total=price*qty;sh_(QUOTATIONS_SHEET).appendRow([id,qno,1,new Date(),u.user_id,p.buyer_company||"",p.buyer_contact||"",p.buyer_email||"",p.country||"",p.item_code||"",p.color||"",qty,req,approved||"",p.currency||"USD",p.incoterm||"FOB Vietnam",p.destination_port||"",p.payment_terms||"",Number(p.validity_days||15),p.lead_time||"",total||"",status,approved>0?u.user_id:"",approved>0?new Date():""]);audit_(u.user_id,"SAVE_QUOTATION",id,"success",status);return {ok:true,quotation_id:id,quotation_no:qno,version:1,status,total_value:total};}
function listQuotations_(p){const u=requireUser_(p),rows=rowsAsObjects_(sh_(QUOTATIONS_SHEET),3).rows;return {ok:true,quotations:(u.role==="admin"||u.role==="staff"?rows:rows.filter(x=>String(x.created_by)===String(u.user_id)))};}
function approveQuotation_(p){const a=requireAdmin_(p),rows=rowsAsObjects_(sh_(QUOTATIONS_SHEET),3).rows,q=rows.find(x=>String(x.quotation_id)===String(p.quotation_id));if(!q)throw new Error("Quotation not found");const price=Number(p.approved_unit_price||0);if(!(price>0))throw new Error("Approved price required");const s=sh_(QUOTATIONS_SHEET),qty=Number(q.quantity||0);s.getRange(q._row,14).setValue(price);s.getRange(q._row,21).setValue(price*qty);s.getRange(q._row,22).setValue("Approved");s.getRange(q._row,23).setValue(a.user_id);s.getRange(q._row,24).setValue(new Date());audit_(a.user_id,"APPROVE_QUOTATION",q.quotation_id,"success",String(price));return {ok:true,status:"Approved",approved_unit_price:price,total_value:price*qty};}
function audit_(actor,action,target,result,details){sh_(AUDIT_SHEET).appendRow(["EVT-"+Date.now(),new Date(),actor,action,target,result,details||"","","Apps Script",""]);}function logAttempt_(id,success,reason){sh_(ATTEMPTS_SHEET).appendRow([new Date(),id,!!success,reason||"","","","",""]);}