const SPREADSHEET_ID="1o7OXEp7FHMrJ2TPqmWXH6BQM25nLqxxdC0J2l6f2O_c";
const S={USERS:"USERS",SESSIONS:"SESSIONS",AUDIT:"AUDIT_LOG",ATTEMPTS:"LOGIN_ATTEMPTS",CUSTOMERS:"CUSTOMERS",DEALS:"DEALS",PRODUCTS:"PRODUCT_MASTER",PROPOSALS:"PROPOSALS",QUOTES:"QUOTATIONS",ACTIVITY:"ACTIVITY_LOG"};
function doGet(e){return handle_(e&&e.parameter?e.parameter:{})} function doPost(e){let p={};try{p=JSON.parse(e&&e.postData?e.postData.contents:"{}")}catch(_){}return handle_(p)}
function handle_(p){try{ensureSchema_();const a=String(p.action||"");const map={health:()=>({ok:true,service:"PEFSO Sales",version:"5.0",soft_delete:true}),login:()=>login_(p),me:()=>me_(p),logout:()=>logout_(p),listUsers:()=>listUsers_(p),saveUser:()=>saveUser_(p),resetPin:()=>resetPin_(p),changeOwnCredentials:()=>changeOwn_(p),setUserActive:()=>setUserActive_(p),listCustomers:()=>listCustomers_(p),saveCustomer:()=>saveCustomer_(p),softDeleteCustomer:()=>setCustomerActive_(p,false),restoreCustomer:()=>setCustomerActive_(p,true),listDeals:()=>listDeals_(p),saveDeal:()=>saveDeal_(p),softDeleteDeal:()=>setDealActive_(p,false),restoreDeal:()=>setDealActive_(p,true),listProducts:()=>listProducts_(p),saveProduct:()=>saveProduct_(p),softDeleteProduct:()=>setProductActive_(p,false),restoreProduct:()=>setProductActive_(p,true),saveProposal:()=>saveProposal_(p),listProposals:()=>listProposals_(p),saveQuotation:()=>saveQuote_(p),listQuotations:()=>listQuotes_(p),approveQuotation:()=>approveQuote_(p),logActivity:()=>logActivity_(p),listActivities:()=>listActivities_(p),dashboard:()=>dashboard_(p),listAudit:()=>listAudit_(p)};if(!map[a])return out_({ok:false,error:"Unknown action"});return out_(map[a]())}catch(e){return out_({ok:false,error:String(e&&e.message?e.message:e)})}}
function out_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function ss_(){return SpreadsheetApp.openById(SPREADSHEET_ID)} function sh_(n){return ss_().getSheetByName(n)} function now_(){return new Date().toISOString()}
function ensureSchema_(){if(!sh_(S.USERS))throw Error("USERS sheet missing");if(!sh_(S.ACTIVITY)){const s=ss_().insertSheet(S.ACTIVITY);s.getRange(1,1).setValue("PEFSO SALES — ACTIVITY LOG");s.getRange(3,1,1,13).setValues([["activity_id","timestamp","user_id","customer_id","deal_id","activity_type","channel","summary","next_action","next_action_date","meaningful","source","active"]])}const u=sh_(S.USERS);if(u.getRange(3,15).getValue()!=="hash_version")u.getRange(3,15).setValue("hash_version");if(u.getRange(3,16).getValue()!=="visible_pin")u.getRange(3,16).setValue("visible_pin")}
function rows_(name,hr=3){const s=sh_(name),lr=s.getLastRow(),lc=s.getLastColumn();if(lr<hr)return[];const v=s.getRange(hr,1,lr-hr+1,lc).getValues(),h=v.shift().map(String);return v.map((r,i)=>{const o={_row:hr+1+i};h.forEach((k,j)=>{if(k)o[k]=r[j]});return o}).filter(o=>Object.keys(o).some(k=>k!=="_row"&&String(o[k]??"")!==""))}
function find_(name,key,val){return rows_(name).find(x=>String(x[key]||"").toLowerCase()===String(val||"").toLowerCase())||null}
function hex_(b){return b.map(x=>{x=x<0?x+256:x;return(x<16?"0":"")+x.toString(16)}).join("")} function sha_(t){return hex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(t),Utilities.Charset.UTF_8))}
function salt_(){return Utilities.getUuid().replace(/-/g,"")+Utilities.getUuid().replace(/-/g,"")} function hash1_(pin,s){return sha_(s+":"+pin)} function pepper_(){const p=PropertiesService.getScriptProperties();let x=p.getProperty("PEFSO_AUTH_PEPPER");if(!x){x=Utilities.getUuid()+Utilities.getUuid();p.setProperty("PEFSO_AUTH_PEPPER",x)}return x} function hash2_(pin,s){return sha_(pepper_()+":"+s+":"+pin)}
function validPin_(p){return /^\d{8}$/.test(String(p||""))}
function findUser_(id){return find_(S.USERS,"user_id",id)}
function safeUser_(u,showPin){return{user_id:u.user_id,role:u.role,display_name:u.display_name,active:u.active,visible_pin:showPin?u.visible_pin:undefined,permissions:{can_manage_users:u.can_manage_users,can_manage_products:u.can_manage_products,can_approve_quotation:u.can_approve_quotation,can_see_all_customers:u.can_see_all_customers,can_manage_prices:u.can_manage_prices}}}
function login_(p){const id=String(p.user_id||"").trim(),pin=String(p.pin||"");if(!id||!validPin_(pin))return{ok:false,error:"Invalid user ID or PIN"};const u=findUser_(id);if(!u||String(u.active).toLowerCase()!=="true"){attempt_(id,false,"inactive_or_missing");return{ok:false,error:"Invalid user ID or PIN"}}const ver=String(u.hash_version||"v1_sha256_salt"),cand=ver==="v2_pepper_sha256"?hash2_(pin,u.salt):hash1_(pin,u.salt);if(cand!==String(u.pin_hash)){attempt_(id,false,"bad_pin");return{ok:false,error:"Invalid user ID or PIN"}}if(ver!=="v2_pepper_sha256"){const s=salt_();const us=sh_(S.USERS);us.getRange(u._row,4).setValue(hash2_(pin,s));us.getRange(u._row,5).setValue(s);us.getRange(u._row,15).setValue("v2_pepper_sha256");u.salt=s;u.hash_version="v2_pepper_sha256"}const tok=sha_(Utilities.getUuid()+Date.now()),th=sha_(tok),issued=new Date(),exp=new Date(issued.getTime()+8*3600000);sh_(S.SESSIONS).appendRow([th,u.user_id,u.role,issued,exp,issued,true,"","","login"]);attempt_(id,true,"");audit_(u.user_id,"LOGIN","USER",u.user_id,null,null,false);return{ok:true,token:tok,user:safeUser_(u,false)}}
function sessionUser_(tok){if(!tok)return null;const h=sha_(tok),s=sh_(S.SESSIONS),v=s.getDataRange().getValues();if(v.length<4)return null;for(let i=3;i<v.length;i++)if(String(v[i][0])===h&&String(v[i][6]).toLowerCase()==="true"&&new Date(v[i][4]).getTime()>Date.now()){const u=findUser_(v[i][1]);if(u&&String(u.active).toLowerCase()==="true"){s.getRange(i+1,6).setValue(new Date());return u}}return null}
function user_(p){const u=sessionUser_(p.token);if(!u)throw Error("Unauthorized");return u} function admin_(p){const u=user_(p);if(u.role!=="admin")throw Error("Admin only");return u}
function me_(p){return{ok:true,user:safeUser_(user_(p),false)}} function logout_(p){if(!p.token)return{ok:true};const h=sha_(p.token),s=sh_(S.SESSIONS),v=s.getDataRange().getValues();for(let i=3;i<v.length;i++)if(String(v[i][0])===h)s.getRange(i+1,7).setValue(false);return{ok:true}}
function rolePerm_(r){if(r==="admin")return[true,true,true,true,true];if(r==="staff")return[false,true,false,true,false];return[false,false,false,false,false]}
function listUsers_(p){admin_(p);return{ok:true,users:rows_(S.USERS).filter(x=>x.user_id).map(x=>safeUser_(x,true))}}
function saveUser_(p){const a=admin_(p),old=String(p.original_user_id||"").trim(),id=String(p.user_id||"").trim(),role=String(p.role||"").trim(),name=String(p.display_name||id).trim();if(!/^[A-Za-z0-9._-]{3,40}$/.test(id))throw Error("Invalid user ID");if(!["admin","staff","collaborator"].includes(role))throw Error("Invalid role");const s=sh_(S.USERS),ex=old?findUser_(old):null,dupe=findUser_(id);if(dupe&&(!ex||dupe._row!==ex._row))throw Error("User ID already exists");const perm=rolePerm_(role);if(ex){const before=JSON.stringify(safeUser_(ex,true));s.getRange(ex._row,1,1,3).setValues([[id,role,name]]);s.getRange(ex._row,7,1,5).setValues([perm]);s.getRange(ex._row,13).setValue(now_());audit_(a.user_id,"UPDATE","USER",id,before,JSON.stringify({id,role,name}),false)}else{if(!validPin_(p.pin))throw Error("New user requires an 8-digit PIN");const sl=salt_();s.appendRow([id,role,name,hash2_(p.pin,sl),sl,true,...perm,now_(),now_(),"Created by "+a.user_id,"v2_pepper_sha256",String(p.pin)]);audit_(a.user_id,"CREATE","USER",id,null,JSON.stringify({id,role,name}),false)}return{ok:true}}
function resetPin_(p){const a=admin_(p),u=findUser_(p.user_id);if(!u)throw Error("User not found");if(!validPin_(p.new_pin))throw Error("PIN must be exactly 8 digits");const s=salt_(),us=sh_(S.USERS);us.getRange(u._row,4).setValue(hash2_(p.new_pin,s));us.getRange(u._row,5).setValue(s);us.getRange(u._row,13).setValue(now_());us.getRange(u._row,15).setValue("v2_pepper_sha256");us.getRange(u._row,16).setValue(String(p.new_pin));invalidate_(u.user_id);audit_(a.user_id,"RESET_PIN","USER",u.user_id,null,"PIN changed",false);return{ok:true}}
function changeOwn_(p){const u=user_(p),live=findUser_(u.user_id),old=String(p.current_pin||""),np=String(p.new_pin||""),nid=String(p.new_user_id||u.user_id).trim();if(!validPin_(old))throw Error("Current PIN required");const ver=String(live.hash_version||"v1_sha256_salt"),chk=ver==="v2_pepper_sha256"?hash2_(old,live.salt):hash1_(old,live.salt);if(chk!==String(live.pin_hash))throw Error("Current PIN incorrect");if(nid!==u.user_id&&findUser_(nid))throw Error("User ID already exists");const s=sh_(S.USERS);s.getRange(live._row,1).setValue(nid);if(np){if(!validPin_(np))throw Error("New PIN must be exactly 8 digits");const sl=salt_();s.getRange(live._row,4).setValue(hash2_(np,sl));s.getRange(live._row,5).setValue(sl);s.getRange(live._row,15).setValue("v2_pepper_sha256");s.getRange(live._row,16).setValue(np)}s.getRange(live._row,13).setValue(now_());invalidate_(u.user_id);audit_(u.user_id,"CHANGE_CREDENTIALS","USER",nid,null,"Own credentials changed",false);return{ok:true}}
function setUserActive_(p){const a=admin_(p),u=findUser_(p.user_id);if(!u)throw Error("User not found");if(u.user_id===a.user_id&&!p.active)throw Error("Cannot deactivate current admin");sh_(S.USERS).getRange(u._row,6).setValue(!!p.active);if(!p.active)invalidate_(u.user_id);audit_(a.user_id,p.active?"RESTORE":"SOFT_DELETE","USER",u.user_id,null,null,!p.active);return{ok:true}}
function invalidate_(id){const s=sh_(S.SESSIONS),v=s.getDataRange().getValues();for(let i=3;i<v.length;i++)if(String(v[i][1])===String(id))s.getRange(i+1,7).setValue(false)}
function isTrue_(v){return v===true||String(v).toLowerCase()==="true"} function canAll_(u){return u.role==="admin"||u.role==="staff"||isTrue_(u.can_see_all_customers)}
function normalize_(s){return String(s||"").toLowerCase().replace(/https?:\/\//g,"").replace(/^www\./,"").split("/")[0].trim()} function nameNorm_(s){return String(s||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function customerView_(u,c){return canAll_(u)||String(c.owner_user_id)===String(u.user_id)}
function listCustomers_(p){const u=user_(p),inc=!!p.include_deleted;return{ok:true,customers:rows_(S.CUSTOMERS).filter(c=>c.customer_id&&customerView_(u,c)&&(inc||isTrue_(c.active))).sort((a,b)=>String(a.company_name).localeCompare(String(b.company_name)))}}
function saveCustomer_(p){const u=user_(p),id=String(p.customer_id||"").trim(),company=String(p.company_name||"").trim();if(!company)throw Error("Company name is required");let web=String(p.website||"").trim(),email=String(p.contact_email||"").trim(),domain=normalize_(web||email.split("@")[1]||"");const nn=nameNorm_(company),country=String(p.country||"").trim();const all=rows_(S.CUSTOMERS).filter(c=>c.customer_id&&isTrue_(c.active)&&c.customer_id!==id);const exact=all.find(c=>domain&&String(c.domain).toLowerCase()===domain.toLowerCase());if(exact)throw Error("Possible duplicate: this website/email domain already exists in PEFSO.");const fuzzy=all.find(c=>nameNorm_(c.company_name)===nn&&String(c.country||"").toLowerCase()===country.toLowerCase());if(fuzzy)throw Error("Possible duplicate: same company name and country already exist.");const s=sh_(S.CUSTOMERS),old=id?find_(S.CUSTOMERS,"customer_id",id):null,owner=u.role==="collaborator"?u.user_id:String(p.owner_user_id||u.user_id),now=now_();if(old){if(!customerView_(u,old))throw Error("Forbidden");const before=JSON.stringify(old);const vals=[company,nn,web,domain,country,old.parent_group||"",String(p.contact_name||""),old.contact_title||"",email,old.phone||"",owner,old.account_status||"Assigned",old.source||"Manual","No duplicate",true,old.created_by,old.created_at,u.user_id,now,old.deleted_by||"",old.deleted_at||"",old.admin_note||""];s.getRange(old._row,2,1,22).setValues([vals]);audit_(u.user_id,"UPDATE","CUSTOMER",id,before,JSON.stringify(vals),false);return{ok:true,customer_id:id}}const nid="CUST-"+Date.now();s.appendRow([nid,company,nn,web,domain,country,"",String(p.contact_name||""),"",email,"",owner,"Assigned","Manual","No duplicate",true,u.user_id,now,u.user_id,now,"","",""]);audit_(u.user_id,"CREATE","CUSTOMER",nid,null,JSON.stringify({company,domain,country,owner}),false);return{ok:true,customer_id:nid}}
function setCustomerActive_(p,on){const u=user_(p),c=find_(S.CUSTOMERS,"customer_id",p.customer_id);if(!c)throw Error("Customer not found");if(!customerView_(u,c))throw Error("Forbidden");const s=sh_(S.CUSTOMERS);s.getRange(c._row,16).setValue(on);s.getRange(c._row,19).setValue(u.user_id);s.getRange(c._row,20).setValue(now_());s.getRange(c._row,21).setValue(on?"":u.user_id);s.getRange(c._row,22).setValue(on?"":now_());audit_(u.user_id,on?"RESTORE":"SOFT_DELETE","CUSTOMER",c.customer_id,JSON.stringify(c),null,!on);return{ok:true}}
function dealView_(u,d){return canAll_(u)||String(d.owner_user_id)===String(u.user_id)}
function listDeals_(p){const u=user_(p),inc=!!p.include_deleted;return{ok:true,deals:rows_(S.DEALS).filter(d=>d.deal_id&&dealView_(u,d)&&(inc||isTrue_(d.active))).sort((a,b)=>String(b.updated_at||"").localeCompare(String(a.updated_at||"")))}}
function saveDeal_(p){const u=user_(p),id=String(p.deal_id||""),cid=String(p.customer_id||""),name=String(p.deal_name||"").trim();if(!cid||!name)throw Error("Customer and deal name are required");const c=find_(S.CUSTOMERS,"customer_id",cid);if(!c||!customerView_(u,c))throw Error("Customer unavailable");const s=sh_(S.DEALS),old=id?find_(S.DEALS,"deal_id",id):null,owner=u.role==="collaborator"?u.user_id:(old?old.owner_user_id:c.owner_user_id||u.user_id),stage=String(p.stage||"Lead"),status=stage==="Won"?"Won":stage==="Lost"?"Lost":"Open",now=now_(),qty=Number(p.estimated_qty||0),tgt=Number(p.customer_target_price_usd||0),lost=String(p.lost_reason||"");if(stage==="Lost"&&!lost)throw Error("Lost reason is required");if(old){if(!dealView_(u,old))throw Error("Forbidden");const before=JSON.stringify(old);const row=old._row;s.getRange(row,2).setValue(cid);s.getRange(row,3).setValue(name);s.getRange(row,4).setValue(owner);s.getRange(row,5).setValue(stage);s.getRange(row,6).setValue(status);s.getRange(row,8).setValue(qty);s.getRange(row,9).setValue(tgt);s.getRange(row,12).setValue(String(p.destination_port||""));s.getRange(row,14).setValue(String(p.next_action||""));s.getRange(row,15).setValue(String(p.next_action_date||""));s.getRange(row,16).setValue(now);s.getRange(row,17).setValue(stage==="Won");s.getRange(row,20).setValue(lost);s.getRange(row,25).setValue(u.user_id);s.getRange(row,26).setValue(now);audit_(u.user_id,"UPDATE","DEAL",id,before,JSON.stringify({stage,status,qty,tgt}),false);return{ok:true,deal_id:id}}const nid="DEAL-"+Date.now();s.appendRow([nid,cid,name,owner,stage,status,"",qty,tgt,0,"USD",String(p.destination_port||""),"",String(p.next_action||""),String(p.next_action_date||""),now,stage==="Won",0,0,lost,"",true,u.user_id,now,u.user_id,now,"","",""]);audit_(u.user_id,"CREATE","DEAL",nid,null,JSON.stringify({cid,name,stage,owner}),false);return{ok:true,deal_id:nid}}
function setDealActive_(p,on){const u=user_(p),d=find_(S.DEALS,"deal_id",p.deal_id);if(!d)throw Error("Deal not found");if(!dealView_(u,d))throw Error("Forbidden");const s=sh_(S.DEALS);s.getRange(d._row,22).setValue(on);s.getRange(d._row,25).setValue(u.user_id);s.getRange(d._row,26).setValue(now_());s.getRange(d._row,27).setValue(on?"":u.user_id);s.getRange(d._row,28).setValue(on?"":now_());audit_(u.user_id,on?"RESTORE":"SOFT_DELETE","DEAL",d.deal_id,JSON.stringify(d),null,!on);return{ok:true}}
function listProducts_(p){const u=user_(p),inc=!!p.include_deleted;return{ok:true,products:rows_(S.PRODUCTS).filter(x=>x.product_id&&(inc||String(x.status).toLowerCase()!=="deleted")).map(x=>{if(!isTrue_(u.can_manage_prices)){delete x.floor_fob_usd;if(u.role==="collaborator")delete x.expected_fob_usd}return x})}}
function saveProduct_(p){const u=user_(p);if(!isTrue_(u.can_manage_products))throw Error("Forbidden");const id=String(p.product_id||""),code=String(p.item_code||"").trim(),name=String(p.product_name||"").trim();if(!code||!name)throw Error("Item code and product name are required");const dup=rows_(S.PRODUCTS).find(x=>String(x.item_code).toLowerCase()===code.toLowerCase()&&x.product_id!==id&&String(x.status).toLowerCase()!=="deleted");if(dup)throw Error("Item code already exists");const s=sh_(S.PRODUCTS),old=id?find_(S.PRODUCTS,"product_id",id):null,now=now_();if(old){const before=JSON.stringify(old);s.getRange(old._row,2).setValue(code);s.getRange(old._row,3).setValue(name);s.getRange(old._row,4).setValue(String(p.color||""));s.getRange(old._row,14).setValue(Number(p.moq_pcs||0));s.getRange(old._row,18).setValue(String(p.image_url||old.image_url||""));if(isTrue_(u.can_manage_prices)){if(p.floor_fob_usd!=="")s.getRange(old._row,16).setValue(Number(p.floor_fob_usd));if(p.expected_fob_usd!=="")s.getRange(old._row,17).setValue(Number(p.expected_fob_usd))}s.getRange(old._row,27).setValue(u.user_id);s.getRange(old._row,28).setValue(now);audit_(u.user_id,"UPDATE","PRODUCT",id,before,null,false);return{ok:true,product_id:id}}const nid="PROD-"+Date.now();s.appendRow([nid,code,name,String(p.color||""),name,5.5,3,2.5,3.5,2.125,"Cement weight","Metallic foil + foil fringe","Standard Balloon Weight construction",Number(p.moq_pcs||97000),"FOB / pc",isTrue_(u.can_manage_prices)?Number(p.floor_fob_usd||0):0,isTrue_(u.can_manage_prices)?Number(p.expected_fob_usd||0):0,String(p.image_url||""),"Manual","Manual","Active","Added in PEFSO Sales","","",u.user_id,now,u.user_id,now]);audit_(u.user_id,"CREATE","PRODUCT",nid,null,JSON.stringify({code,name}),false);return{ok:true,product_id:nid}}
function setProductActive_(p,on){const u=user_(p);if(!isTrue_(u.can_manage_products))throw Error("Forbidden");const x=find_(S.PRODUCTS,"product_id",p.product_id);if(!x)throw Error("Product not found");const s=sh_(S.PRODUCTS);s.getRange(x._row,21).setValue(on?"Active":"Deleted");s.getRange(x._row,23).setValue(on?"":u.user_id);s.getRange(x._row,24).setValue(on?"":now_());s.getRange(x._row,27).setValue(u.user_id);s.getRange(x._row,28).setValue(now_());audit_(u.user_id,on?"RESTORE":"SOFT_DELETE","PRODUCT",x.product_id,JSON.stringify(x),null,!on);return{ok:true}}
function saveProposal_(p){const u=user_(p),c=find_(S.CUSTOMERS,"customer_id",p.customer_id);if(!c||!customerView_(u,c))throw Error("Customer required");const d=p.deal_id?find_(S.DEALS,"deal_id",p.deal_id):null;if(d&&!dealView_(u,d))throw Error("Deal unavailable");const ids=(p.selected_product_ids||[]).map(String),codes=ids.map(id=>find_(S.PRODUCTS,"product_id",id)).filter(Boolean).map(x=>x.item_code).join(","),id="PROP-"+Date.now();sh_(S.PROPOSALS).appendRow([id,now_(),u.user_id,c.company_name,c.contact_name,c.contact_email,c.country,codes,String(p.buyer_context||""),String(p.recommended_direction||""),"",String(p.next_step||""),"Draft","","Customer ID="+c.customer_id+"; Deal ID="+String(p.deal_id||"")]);audit_(u.user_id,"CREATE","PROPOSAL",id,null,JSON.stringify({customer:c.customer_id,deal:p.deal_id,codes}),false);return{ok:true,proposal_id:id}}
function listProposals_(p){const u=user_(p);return{ok:true,proposals:rows_(S.PROPOSALS).filter(x=>canAll_(u)||String(x.created_by)===u.user_id)}}
function nextQuoteNo_(){const y=new Date().getFullYear(),qs=rows_(S.QUOTES).filter(x=>String(x.quotation_no||"").startsWith("QT-"+y+"-"));let n=qs.map(x=>Number(String(x.quotation_no).split("-").pop())||0).reduce((a,b)=>Math.max(a,b),0)+1;return"QT-"+y+"-"+String(n).padStart(4,"0")}
function saveQuote_(p){const u=user_(p),c=find_(S.CUSTOMERS,"customer_id",p.customer_id),d=p.deal_id?find_(S.DEALS,"deal_id",p.deal_id):null,prod=find_(S.PRODUCTS,"product_id",p.product_id);if(!c||!customerView_(u,c))throw Error("Customer required");if(d&&!dealView_(u,d))throw Error("Deal unavailable");if(!prod)throw Error("Product required");const no=nextQuoteNo_(),ver=1,id=no+"-V1",qty=Number(p.quantity||0),req=Number(p.requested_unit_price||0);if(qty<=0)throw Error("Quantity must be greater than zero");sh_(S.QUOTES).appendRow([id,no,ver,now_(),u.user_id,c.company_name,c.contact_name,c.contact_email,c.country,prod.item_code,prod.color,qty,req,0,"USD",String(p.incoterm||"FOB Vietnam"),String(p.destination_port||""),String(p.payment_terms||""),Number(p.validity_days||15),String(p.lead_time||""),0,"Pending Approval","","",c.customer_id,String(p.deal_id||""),false,"",""]);audit_(u.user_id,"CREATE","QUOTATION",id,null,JSON.stringify({no,qty,req,customer:c.customer_id}),false);return{ok:true,quotation_id:id,quotation_no:no,version:ver}}
function quoteView_(u,q){return canAll_(u)||String(q.created_by)===u.user_id}
function listQuotes_(p){const u=user_(p);return{ok:true,quotations:rows_(S.QUOTES).filter(q=>q.quotation_id&&quoteView_(u,q)).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)))}}
function approveQuote_(p){const a=admin_(p),q=find_(S.QUOTES,"quotation_id",p.quotation_id);if(!q)throw Error("Quotation not found");const price=Number(p.approved_unit_price||0);if(price<=0)throw Error("Approved price required");const s=sh_(S.QUOTES),before=JSON.stringify(q);s.getRange(q._row,14).setValue(price);s.getRange(q._row,21).setValue(Number(q.quantity||0)*price);s.getRange(q._row,22).setValue("Approved");s.getRange(q._row,23).setValue(a.user_id);s.getRange(q._row,24).setValue(now_());s.getRange(q._row,27).setValue(true);s.getRange(q._row,28).setValue(now_());audit_(a.user_id,"APPROVE","QUOTATION",q.quotation_id,before,JSON.stringify({price}),false);return{ok:true}}
function logActivity_(p){const u=user_(p),c=find_(S.CUSTOMERS,"customer_id",p.customer_id),d=p.deal_id?find_(S.DEALS,"deal_id",p.deal_id):null;if(!c||!customerView_(u,c))throw Error("Customer required");if(d&&!dealView_(u,d))throw Error("Deal unavailable");if(!String(p.summary||"").trim())throw Error("Summary is required");const id="ACT-"+Date.now(),now=now_();sh_(S.ACTIVITY).appendRow([id,now,u.user_id,c.customer_id,String(p.deal_id||""),String(p.activity_type||""),String(p.channel||""),String(p.summary||""),String(p.next_action||""),String(p.next_action_date||""),!!p.meaningful,"App",true]);if(d){const s=sh_(S.DEALS);s.getRange(d._row,14).setValue(String(p.next_action||d.next_action||""));s.getRange(d._row,15).setValue(String(p.next_action_date||d.next_action_date||""));s.getRange(d._row,16).setValue(now);s.getRange(d._row,25).setValue(u.user_id);s.getRange(d._row,26).setValue(now)}audit_(u.user_id,"CREATE","ACTIVITY",id,null,JSON.stringify({customer:c.customer_id,deal:p.deal_id,type:p.activity_type}),false);return{ok:true,activity_id:id}}
function listActivities_(p){const u=user_(p),a=rows_(S.ACTIVITY).filter(x=>x.activity_id&&(canAll_(u)||String(x.user_id)===u.user_id)&&isTrue_(x.active));a.sort((x,y)=>String(y.timestamp).localeCompare(String(x.timestamp)));return{ok:true,activities:a}}
function dashboard_(p){const u=user_(p),cs=rows_(S.CUSTOMERS).filter(c=>c.customer_id&&isTrue_(c.active)&&customerView_(u,c)),ds=rows_(S.DEALS).filter(d=>d.deal_id&&isTrue_(d.active)&&dealView_(u,d)),qs=rows_(S.QUOTES).filter(q=>q.quotation_id&&quoteView_(u,q)),ps=rows_(S.PROPOSALS).filter(x=>canAll_(u)||String(x.created_by)===u.user_id),as=rows_(S.ACTIVITY).filter(x=>x.activity_id&&(canAll_(u)||String(x.user_id)===u.user_id)&&isTrue_(x.active)),cut=Date.now()-7*86400000,users=rows_(S.USERS).filter(x=>x.user_id&&String(x.active).toLowerCase()==="true"&&["staff","collaborator"].includes(String(x.role)));const scope=canAll_(u)?users:[u];const team=scope.map(x=>{const uid=x.user_id,act=as.filter(a=>a.user_id===uid&&new Date(a.timestamp).getTime()>=cut);return{user_id:uid,activities_7d:act.length,meaningful_7d:act.filter(a=>isTrue_(a.meaningful)).length,customers:rows_(S.CUSTOMERS).filter(c=>isTrue_(c.active)&&c.owner_user_id===uid).length,open_deals:rows_(S.DEALS).filter(d=>isTrue_(d.active)&&d.owner_user_id===uid&&d.status==="Open").length,proposals:rows_(S.PROPOSALS).filter(z=>z.created_by===uid).length,quotations:rows_(S.QUOTES).filter(z=>z.created_by===uid).length,won:rows_(S.DEALS).filter(d=>isTrue_(d.active)&&d.owner_user_id===uid&&d.status==="Won").length}});const pipe={Lead:0,Qualified:0,Proposal:0,Sample:0,Quotation:0,Negotiation:0,Won:0,Lost:0,"On hold":0};ds.forEach(d=>{const k=pipe[d.stage]!==undefined?d.stage:d.status;if(pipe[k]!==undefined)pipe[k]++});return{ok:true,kpi:{customers:cs.length,open_deals:ds.filter(d=>d.status==="Open").length,pending_quotes:qs.filter(q=>q.status==="Pending Approval").length,activities_7d:as.filter(a=>new Date(a.timestamp).getTime()>=cut).length},team,pipeline:pipe}}
function listAudit_(p){admin_(p);const e=rows_(S.AUDIT).filter(x=>x.event_id);e.sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp)));return{ok:true,events:e}}
function audit_(actor,action,entity,target,before,after,soft){sh_(S.AUDIT).appendRow(["EVT-"+Date.now(),now_(),actor,action,target,"success","",sha_(actor).slice(0,8),"Apps Script","",entity,before||"",after||"",!!soft])}
function attempt_(id,ok,reason){sh_(S.ATTEMPTS).appendRow([new Date(),id,!!ok,reason||"","","","",""])}